import './globals.css'
import { Providers } from './Providers'


export const metadata = {
  title: 'Biggan PathShala ',
  description: 'Generated by Rownok',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className="">
        <main className=''>
          <Providers>
           
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
