import { Footer } from '../Footer';
import NavBar from '../Navbar'
export const metadata = {
  title: 'Biggan PathShala ',
  description: 'Generated by Rownok',
}

export default function RootLayout({ children }) {
  return (
   
        <main className=''>
        <NavBar/>
            {children}
    <Footer/>
        </main>
     
  );
}
